export const elements = [
  {
    number: 60,
    urls: [
      'slike/priroda/Evergreen.png',
      'slike/priroda/A_Lumpy_Evergreen.png',
    ],
  },
  {
    number: 10,
    urls: [
      'slike/zgrade/kuca-bunker.png',
      'slike/zgrade/kuca-01.png',
      'slike/stvari/balvani-02.png',
      'slike/stvari/ograda-01.png',
      'slike/stvari/vrece-s-peskom.png',
      'slike/stvari/zidic-07.png',
      'slike/partizani/tenkovi/tenk-04.png',
      'slike/partizani/vozila/dzip-01.png',
    ],
  },
  {
    number: 100,
    urls: [
      'slike/partizani/bolnicari/bolnicarka-02.png',
      'slike/partizani/vojnici/komesar-01.png',
      'slike/partizani/vojnici/komesar-02.png',
      'slike/partizani/vojnici/mp40-05.png',
      'slike/partizani/vojnici/partizan-01.png',
      'slike/partizani/vojnici/partizan-01-sledja.png',
      'slike/partizani/vojnici/partizan-02.png',
      'slike/partizani/vojnici/partizan-03.png',
      'slike/partizani/vojnici/partizan-04.png',
      'slike/partizani/vojnici/partizan-05.png',
      'slike/partizani/vojnici/partizan-07.png',
      'slike/partizani/vojnici/partizan-08.png',
      'slike/partizani/vojnici/partizan-09.png',
      'slike/partizani/vojnici/partizan-10.png',
      'slike/partizani/vojnici/partizan-11.png',
      'slike/partizani/vojnici/partizan-12.png',
      'slike/partizani/vojnici/partizan-13.png',
      'slike/partizani/vojnici/partizan-14.png',
      'slike/partizani/vojnici/partizan-17.png',
      'slike/partizani/vojnici/partizan-18.png',
      'slike/partizani/vojnici/partizan-21.png',
      'slike/partizani/vojnici/partizan-24.png',
      'slike/partizani/vojnici/partizan-25.png',
      'slike/partizani/vojnici/partizan-28.png',
      'slike/partizani/vojnici/partizan-30.png',
      'slike/partizani/vojnici/stoji-02.png',
      'slike/partizani/marshal-tito.png',
      'slike/rusi/vojnici/zene/borkinja-01.png',
      'slike/rusi/vojnici/zene/borkinja-02.png',
      'slike/rusi/vojnici/zene/borkinja-04.png',
      'slike/rusi/vojnici/zene/mitraljeskinja-01.png',
      'slike/rusi/vojnici/bombas-01.png',
      'slike/rusi/vojnici/bombas-04.png',
      'slike/rusi/vojnici/vojnik-08.png',
      'slike/rusi/vojnici/vojnik-13.png',
      'slike/rusi/vojnici/zastavnik-01.png',
      'slike/rusi/vojnici/zastavnik-04.png',
    ],
  },
  {
    number: 15,
    range: { x: 10, y: 0.5, z: 10 },
    origin: { x: 0, y: 2.5, z: 0 },
    urls: [
      'slike/nemci/avioni/avion-03.png',
      'slike/nemci/avioni/dornier-do-355-01.png',
      'slike/nemci/avioni/fieseler-fi-156.png',
      'slike/nemci/avioni/focke-wulf-fw-190.png',
      'slike/nemci/avioni/fw-190f-8.png',
      'slike/ndh/avioni/fi156d.png',
    ],
  },
  {
    number: 10,
    range: { x: 10, y: 0.5, z: 10 },
    origin: { x: 0, y: 1.5, z: 0 },
    urls: [
      'slike/nemci/padobranci/padobranac-01.png',
      'slike/nemci/padobranci/padobranac-03.png',
    ],
  },
]
